name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 2.1.300
    
    - name: Setup libssl
      run: sudo apt install libssl1.1

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Test
      run: dotnet test EscherAuthTests